### PR TITLE
Share action

### PR DESCRIPTION
**Pull request by rocxteady**
Fix https://github.com/readium/r2-testapp-swift/issues/343

Change share enum value from "shareSelection:" to "_share:" in EditingAction since the "_share:" is the official share menu item in iOS system.

Also added for checking the sharing enabled for adding a custom UIMenuItem. (I really don't know why there is a custom share option.) I am open to suggestions.

This change copied from the tag 1.2.6 since we still use it. But it should also work with develop branch.

This pull request is sponsored by VIVIDLIPI(https://github.com/mooka-ventures) - www.vividlipi.com (Mooka Ventures Pvt Ltd).

### CODE REVIEW

**Review by mickael-menu — CHANGES_REQUESTED** [review]
@rocxteady Hi, thanks for your contribution!

1. We're actually not using `_share:` on purpose, because iOS doesn't let us override this function compared to `copy:`. We need to override it to control that the user is not copying more than allowed with DRM protected publications. Maybe you can add the following comment above  `case share = "shareSelection:"` to make it clearer?

```
// Note: We need to override the share action to check the copy rights with protected publications. Unfortunately, overriding the native `_share:` action is not possible, so we create our own.
```

2. The check you added when adding the custom Share action seems to fix https://github.com/readium/r2-testapp-swift/issues/343 for EPUBs, thanks! We still have the issue with PDF but we will probably need method sizzling to fix this one.

3. We're only accepting PR over `develop`, because `master` is merged from `develop`. I tried changing the base branch but it's adding some extra commits in the history. Would you mind opening a new PR on `develop`?

**Comment by rocxteady** [comment]
So we don't have to change the string from "shareSelection:" to "_share:" then. I did not know that you had to create a custom share sheet. I did not know the functionality. The problem is then there was no check for adding the custom share menu item. I will restore the editing action item. And if the developer selects the share action the custom share action will be displayed. Is that okay?

**Comment by rocxteady** [comment]
I tried to change it but I have a question. Why do I get an error about coping while trying to share the selected text? I really need to understand the editing action mechanism. :)

**Comment by mickael-menu** [comment]
>  And if the developer selects the share action the custom share action will be displayed. Is that okay?

Yes that's what we want.

> Why do I get an error about coping while trying to share the selected text?

Not sure, this should only happen with a protected publication (e.g. LCP) with no copy right left. Also it could happen if Share was not enabled in the editing actions, but somehow the menu item still appears.

> Can we talk about this issue maybe when you are free?

Sure, you can join me on Slack at http://readium-slack.herokuapp.com/

**Review by mickael-menu — APPROVED** [review]
@rocxteady I reviewed this PR again since it was stalled and it is good to go for me. Let me know on Slack if you want to talk about editing actions.

**Pull request merged**
