### PR TITLE
Fix EPUB navigator set-up issues

### PR DESCRIPTION
**Pull request by ettore**
Address the behavior described in issue #153:

- Fix `PageLocation::isStart` computed variable for `.locator` case.
- Add comments from the discussion of issue #153 to further explain the reasoning behind some of the hard-coded delays used to cope with the web view layout process.
- Customize ad-hoc polling interval for updating user settings styles by iOS version.

With regard to the last point, I'm not very proud of this solution but it's the only one that seemed reliable enough without changing too much of how the EPUB navigator currently works. These values derive from observations debugging issue #153 on physical devices and they try to be pretty generous because there are variable outside of our control that these delays need to deal with.

One option I considered is to delegate the polling interval value to the caller, via an additional `EPUBNavigatorViewController::Configuration` parameter. I'm not sure that's better though. It will expose an implementation detail to the clients, putting the onus on them to figure out what's the correct polling interval to use, for something they are not (and should not be) familiar with. Really this is the responsibility of the navigator and the QA of this should not fall on clients, IMO.

Speaking of QA, I have tested this fix on all iOS simulators down to iOS 10.3.1. For physical devices, I was  helped by the SimplyE team (@jbdalton, @ErnestFan, Sultan Mahmud and @antlong which I thank dearly!) and we tested this fix on the following iOS versions and devices:

iOS 12.5.1: iPhone 6, iPad mini 2 (Model A1490)
iOS 13.6: iPhone Xr
iOS 13.7: iPhone 7
iOS 14.0: iPhone 7
iOS 14.3: iPhone X
iOS 14.4: iPhone X, iPhone XS, iPhone 11

### CODE REVIEW

**Comment by mickael-menu** [comment]
@ettore Thanks! I converted your PR to a draft, just set it as ready for review when you are done. What else do you need to do in this PR?

**Comment by ettore** [comment]
> @ettore Thanks! I converted your PR to a draft, just set it as ready for review when you are done. What else do you need to do in this PR?

ha, I was hoping to add my other change for the timers / delays tweaks, but since they only work on simulators I suppose I should not.

**Comment by mickael-menu** [comment]
Okay, I suggest we wait a few days in case you find something else before merging this PR then.

**Review by mickael-menu — APPROVED** [review]
Awesome, thanks!

> One option I considered is to delegate the polling interval value to the caller, via an additional EPUBNavigatorViewController::Configuration parameter. I'm not sure that's better though. It will expose an implementation detail to the clients, putting the onus on them to figure out what's the correct polling interval to use, for something they are not (and should not be) familiar with. Really this is the responsibility of the navigator and the QA of this should not fall on clients, IMO.

Yeah I would really like to avoid exposing this, we need to handle it properly in the navigator itself.

**Pull request merged**
